spring.application.name=myfirstapp
spring.datasource.url=jdbc:mysql://localhost:3306/support_system
spring.datasource.username=root
spring.datasource.password=root
#isse Database me table automatic update ho jaegi Entity k variables k according (var add krne pr purani table delete krke new nahi banani pdegi)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true